run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errname
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - maintidx
    - nolintlint
    - perfsprint
    - prealloc
    - staticcheck
    - typecheck
    - unused
    - whitespace

linters-settings:
  gofmt:
    simplify: true
