// Code generated by go.m8.ru/cef, DO NOT EDIT.

package cef

import (
	"errors"
	"net"
	"strconv"
)

func (cef *CEF) set(key string, val string) error {
	switch key {
	case "act":
		cef.SetAct(val)

	case "app":
		cef.SetApp(val)

	case "c6a1":
		cef.SetC6a1(net.ParseIP(val))

	case "c6a1Label":
		cef.SetC6a1Label(val)

	case "c6a3":
		cef.SetC6a3(net.ParseIP(val))

	case "c6a3Label":
		cef.SetC6a3Label(val)

	case "c6a4":
		cef.SetC6a4(net.ParseIP(val))

	case "c6a4Label":
		cef.SetC6a4Label(val)

	case "cat":
		cef.SetCat(val)

	case "cfp1":
		cfp1, err := strconv.ParseFloat(val, 32)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCfp1(float32(cfp1))

	case "cfp1Label":
		cef.SetCfp1Label(val)

	case "cfp2":
		cfp2, err := strconv.ParseFloat(val, 32)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCfp2(float32(cfp2))

	case "cfp2Label":
		cef.SetCfp2Label(val)

	case "cfp3":
		cfp3, err := strconv.ParseFloat(val, 32)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCfp3(float32(cfp3))

	case "cfp3Label":
		cef.SetCfp3Label(val)

	case "cfp4":
		cfp4, err := strconv.ParseFloat(val, 32)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCfp4(float32(cfp4))

	case "cfp4Label":
		cef.SetCfp4Label(val)

	case "cn1":
		cn1, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCn1(cn1)

	case "cn1Label":
		cef.SetCn1Label(val)

	case "cn2":
		cn2, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCn2(cn2)

	case "cn2Label":
		cef.SetCn2Label(val)

	case "cn3":
		cn3, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCn3(cn3)

	case "cn3Label":
		cef.SetCn3Label(val)

	case "cnt":
		cnt, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCnt(cnt)

	case "cs1":
		cef.SetCs1(val)

	case "cs1Label":
		cef.SetCs1Label(val)

	case "cs2":
		cef.SetCs2(val)

	case "cs2Label":
		cef.SetCs2Label(val)

	case "cs3":
		cef.SetCs3(val)

	case "cs3Label":
		cef.SetCs3Label(val)

	case "cs4":
		cef.SetCs4(val)

	case "cs4Label":
		cef.SetCs4Label(val)

	case "cs5":
		cef.SetCs5(val)

	case "cs5Label":
		cef.SetCs5Label(val)

	case "cs6":
		cef.SetCs6(val)

	case "cs6Label":
		cef.SetCs6Label(val)

	case "destinationDnsDomain":
		cef.SetDestinationDNSDomain(val)

	case "destinationServiceName":
		cef.SetDestinationServiceName(val)

	case "destinationTranslatedAddress":
		cef.SetDestinationTranslatedAddress(net.ParseIP(val))

	case "destinationTranslatedPort":
		destinationTranslatedPort, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDestinationTranslatedPort(destinationTranslatedPort)

	case "deviceCustomDate1":
		cef.SetDeviceCustomDate1(val)

	case "deviceCustomDate1Label":
		cef.SetDeviceCustomDate1Label(val)

	case "deviceCustomDate2":
		cef.SetDeviceCustomDate2(val)

	case "deviceCustomDate2Label":
		cef.SetDeviceCustomDate2Label(val)

	case "deviceDirection":
		deviceDirection, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDeviceDirection(deviceDirection)

	case "deviceDnsDomain":
		cef.SetDeviceDNSDomain(val)

	case "deviceExternalId":
		cef.SetDeviceExternalID(val)

	case "deviceFacility":
		cef.SetDeviceFacility(val)

	case "deviceInboundInterface":
		cef.SetDeviceInboundInterface(val)

	case "deviceNtDomain":
		cef.SetDeviceNtDomain(val)

	case "deviceOutboundInterface":
		cef.SetDeviceOutboundInterface(val)

	case "DevicePayloadId":
		cef.SetDevicePayloadID(val)

	case "deviceProcessName":
		cef.SetDeviceProcessName(val)

	case "deviceTranslatedAddress":
		cef.SetDeviceTranslatedAddress(net.ParseIP(val))

	case "dhost":
		cef.SetDHost(val)

	case "dntdom":
		cef.SetDntdom(val)

	case "dpid":
		dpid, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDPID(dpid)

	case "dpriv":
		cef.SetDpriv(val)

	case "dproc":
		cef.SetDproc(val)

	case "dpt":
		dpt, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDpt(dpt)

	case "dst":
		cef.SetDst(net.ParseIP(val))

	case "dtz":
		cef.SetDtz(val)

	case "duid":
		cef.SetDuid(val)

	case "duser":
		cef.SetDuser(val)

	case "dvc":
		cef.SetDvc(net.ParseIP(val))

	case "dvchost":
		cef.SetDvchost(val)

	case "dvcmac":
		dvcmac, err := net.ParseMAC(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDvcmac(dvcmac)

	case "dvcpid":
		dvcpid, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDvcpid(dvcpid)

	case "end":
		cef.SetEnd(val)

	case "externalId":
		cef.SetExternalID(val)

	case "fileCreateTime":
		cef.SetFileCreateTime(val)

	case "fileHash":
		cef.SetFileHash(val)

	case "fileId":
		cef.SetFileID(val)

	case "fileModificationTime":
		cef.SetFileModificationTime(val)

	case "filePath":
		cef.SetFilePath(val)

	case "filePermission":
		cef.SetFilePermission(val)

	case "fileType":
		cef.SetFileType(val)

	case "flexDate1":
		cef.SetFlexDate1(val)

	case "flexDate1Label":
		cef.SetFlexDate1Label(val)

	case "flexString1":
		cef.SetFlexString1(val)

	case "flexString1Label":
		cef.SetFlexString1Label(val)

	case "flexString2":
		cef.SetFlexString2(val)

	case "flexString2Label":
		cef.SetFlexString2Label(val)

	case "fname":
		cef.SetFname(val)

	case "fsize":
		fsize, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetFsize(fsize)

	case "in":
		in, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetIn(in)

	case "msg":
		cef.SetMsg(val)

	case "oldFileCreateTime":
		cef.SetOldFileCreateTime(val)

	case "oldFileHash":
		cef.SetOldFileHash(val)

	case "oldFileId":
		cef.SetOldFileID(val)

	case "oldFileModificationTime":
		cef.SetOldFileModificationTime(val)

	case "oldFileName":
		cef.SetOldFileName(val)

	case "oldFilePath":
		cef.SetOldFilePath(val)

	case "oldFilePermission":
		cef.SetOldFilePermission(val)

	case "oldFileSize":
		oldFileSize, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetOldFileSize(oldFileSize)

	case "oldFileType":
		cef.SetOldFileType(val)

	case "out":
		out, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetOut(out)

	case "outcome":
		cef.SetOutcome(val)

	case "proto":
		cef.SetProto(val)

	case "reason":
		cef.SetReason(val)

	case "request":
		cef.SetRequest(val)

	case "requestClientApplication":
		cef.SetRequestClientApplication(val)

	case "requestContext":
		cef.SetRequestContext(val)

	case "requestCookies":
		cef.SetRequestCookies(val)

	case "requestMethod":
		cef.SetRequestMethod(val)

	case "rt":
		cef.SetRt(val)

	case "shost":
		cef.SetShost(val)

	case "smac":
		smac, err := net.ParseMAC(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSmac(smac)

	case "sntdom":
		cef.SetSntdom(val)

	case "sourceDnsDomain":
		cef.SetSourceDNSDomain(val)

	case "sourceServiceName":
		cef.SetSourceServiceName(val)

	case "sourceTranslatedAddress":
		cef.SetSourceTranslatedAddress(net.ParseIP(val))

	case "sourceTranslatedPort":
		sourceTranslatedPort, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSourceTranslatedPort(sourceTranslatedPort)

	case "spid":
		spid, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSpid(spid)

	case "spriv":
		cef.SetSpriv(val)

	case "sproc":
		cef.SetSproc(val)

	case "spt":
		spt, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSpt(spt)

	case "src":
		cef.SetSrc(net.ParseIP(val))

	case "start":
		cef.SetStart(val)

	case "suid":
		cef.SetSuid(val)

	case "suser":
		cef.SetSuser(val)

	case "type":
		typ, err := strconv.Atoi(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetType(typ)

	case "agentDnsDomain":
		cef.SetAgentDNSDomain(val)

	case "agentNtDomain":
		cef.SetAgentNtDomain(val)

	case "agentTranslatedAddress":
		cef.SetAgentTranslatedAddress(net.ParseIP(val))

	case "agentTranslatedZoneExternalID":
		cef.SetAgentTranslatedZoneExternalID(val)

	case "agentTranslatedZoneURI":
		cef.SetAgentTranslatedZoneURI(val)

	case "agentZoneExternalID":
		cef.SetAgentZoneExternalID(val)

	case "agentZoneURI":
		cef.SetAgentZoneURI(val)

	case "agt":
		cef.SetAgt(net.ParseIP(val))

	case "ahost":
		cef.SetAhost(val)

	case "aid":
		cef.SetAid(val)

	case "amac":
		amac, err := net.ParseMAC(val)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetAmac(amac)

	case "art":
		cef.SetArt(val)

	case "at":
		cef.SetAt(val)

	case "atz":
		cef.SetAtz(val)

	case "av":
		cef.SetAv(val)

	case "customerExternalID":
		cef.SetCustomerExternalID(val)

	case "customerURI":
		cef.SetCustomerURI(val)

	case "destinatioTranslatedZoneExternalID":
		cef.SetDestinatioTranslatedZoneExternalID(val)

	case "destinationTranslatedZoneURI":
		cef.SetDestinationTranslatedZoneURI(val)

	case "destinationZoneExternalID":
		cef.SetDestinationZoneExternalID(val)

	case "destinationZoneURI":
		cef.SetDestinationZoneURI(val)

	case "deviceTranslatedZoneExternalID":
		cef.SetDeviceTranslatedZoneExternalID(val)

	case "deviceTranslatedZoneURI":
		cef.SetDeviceTranslatedZoneURI(val)

	case "deviceZoneExternalID":
		cef.SetDeviceZoneExternalID(val)

	case "deviceZoneURI":
		cef.SetDeviceZoneURI(val)

	case "dlat":
		dlat, err := strconv.ParseFloat(val, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDlat(dlat)

	case "dlong":
		dlong, err := strconv.ParseFloat(val, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDlong(dlong)

	case "eventId":
		eventID, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetEventID(eventID)

	case "rawEvent":
		cef.SetRawEvent(val)

	case "slat":
		slat, err := strconv.ParseFloat(val, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSlat(slat)

	case "slong":
		slong, err := strconv.ParseFloat(val, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSlong(slong)

	case "sourceTranslatedZoneExternalID":
		cef.SetSourceTranslatedZoneExternalID(val)

	case "sourceTranslatedZoneURI":
		cef.SetSourceTranslatedZoneURI(val)

	case "sourceZoneExternalID":
		cef.SetSourceZoneExternalID(val)

	case "sourceZoneURI":
		cef.SetSourceZoneURI(val)

	case "agentTranslatedZoneKey":
		agentTranslatedZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetAgentTranslatedZoneKey(agentTranslatedZoneKey)

	case "agentZoneKey":
		agentZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetAgentZoneKey(agentZoneKey)

	case "customerKey":
		customerKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetCustomerKey(customerKey)

	case "destinationTranslatedZoneKey":
		destinationTranslatedZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDestinationTranslatedZoneKey(destinationTranslatedZoneKey)

	case "dZoneKey":
		dZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDZoneKey(dZoneKey)

	case "deviceTranslatedZoneKey":
		deviceTranslatedZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDeviceTranslatedZoneKey(deviceTranslatedZoneKey)

	case "deviceZoneKey":
		deviceZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetDeviceZoneKey(deviceZoneKey)

	case "sTranslatedZoneKey":
		sTranslatedZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSTranslatedZoneKey(sTranslatedZoneKey)

	case "sZoneKey":
		sZoneKey, err := strconv.ParseInt(val, 10, 64)
		if err != nil {
			return errors.Join(err, ErrBadExtension)
		}

		cef.SetSZoneKey(sZoneKey)

	default:
	}

	return nil
}
